#!/bin/bash

flyctl secrets set \
    HOME_SSH_ID_ED25519_BASE64=$(base64 -w 0 home/.ssh/id_ed25519) \
    ETC_SSH_SSH_HOST_ECDSA_KEY_BASE64=$(base64 -w 0 etc/ssh/ssh_host_ecdsa_key) \
    ETC_SSH_SSH_HOST_RSA_KEY_BASE64=$(base64 -w 0 etc/ssh/ssh_host_rsa_key) \
    ETC_SSH_SSH_HOST_ED25519_KEY_BASE64=$(base64 -w 0 etc/ssh/ssh_host_ed25519_key)