#!/bin/bash

set -e

echo "Creating /run/sshd"
mkdir -p /run/sshd

echo "Decoding and writing SSH host keys"

echo "$HOME_SSH_ID_ED25519_BASE64" | base64 -d > /home/$USER_ARG/.ssh/id_ed25519
echo "$HOME_SSH_ID_ED25519_PUB" > /home/$USER_ARG/.ssh/id_ed25519.pub
chmod 0600 /home/$USER_ARG/.ssh/id_ed25519
chown -R $USER_ARG /home/$USER_ARG/.ssh

echo "$ETC_SSH_SSH_HOST_ECDSA_KEY_BASE64" | base64 -d > /etc/ssh/ssh_host_ecdsa_key
echo "$ETC_SSH_SSH_HOST_ECDSA_KEY_PUB" > /etc/ssh/ssh_host_ecdsa_key.pub
chmod 0600 /etc/ssh/ssh_host_ecdsa_key

echo "$ETC_SSH_SSH_HOST_RSA_KEY_BASE64" | base64 -d > /etc/ssh/ssh_host_rsa_key
echo "$ETC_SSH_SSH_HOST_RSA_KEY_PUB" > /etc/ssh/ssh_host_rsa_key.pub
chmod 0600 /etc/ssh/ssh_host_rsa_key

echo "$ETC_SSH_SSH_HOST_ED25519_KEY_BASE64" | base64 -d > /etc/ssh/ssh_host_ed25519_key
echo "$ETC_SSH_SSH_HOST_ED25519_KEY_PUB" > /etc/ssh/ssh_host_ed25519_key.pub
chmod 0600 /etc/ssh/ssh_host_ed25519_key

echo "Symlinking ~/.config and ~/.vscode-server to the data mount"
mkdir -p /data/.config
ln -s /data/.config /home/$USER_ARG/.config

mkdir -p /data/.vscode-server
ln -s /data/.vscode-server /home/$USER_ARG/.vscode-server

echo "Chowning $USER_ARG on /data recursively"
chown -R $USER_ARG /data

echo "Running $@"

exec "$@"