# fly.toml file generated for vscode-remote-example on 2020-11-06T17:32:56Z

app = "vscode-remote-example"

[[services]]
internal_port = 22
protocol = "tcp"

[[services.ports]]
port = 10022

[[mounts]]
source = "data"
destination = "/data"

[env]
HOME_SSH_AUTHORIZED_KEYS = '''
<please run `./generate_fly_toml` or add your ssh public keys here>
'''
