#!/bin/bash

set -e

AUTHORIZED_KEYS=""

for i in ~/.ssh/*.pub; do
    AUTHORIZED_KEYS="$AUTHORIZED_KEYS$(cat $i)\n"
done

echo ""
echo "Set this in your fly.toml:"
echo ""
echo "\
app = \"your-app-name\"

[[services]]
internal_port = 22
protocol = \"tcp\"

[[services.ports]]
port = 10022

[[mounts]]
source = \"data\"
destination = \"/data\"

[env]
HOME_SSH_AUTHORIZED_KEYS = '''
$AUTHORIZED_KEYS
'''
"